apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: sre-capstone
spec:
  type: ClusterIP
  selector:
    app: fastapi-app
  ports:
    - name: http
      port: 8000
      targetPort: 8000